- genie-client/src/main/python/genie/__init__.py
- genie-client/src/main/python/genie/conf.py
- genie-client/src/main/python/genie/exceptions.py
- genie-client/src/main/python/genie/genie.ini
- genie-client/src/main/python/genie/utils.py
- genie-client/src/main/python/tests/genie.ini
- genie-client/src/main/python/tests/test_conf.py
- genie-client/src/main/python/tests/test_utils.py
Adding code to load configuration for the Genie Python client to use
when submitting jobs.
> [#163] Added code for loading Genie config for Python client

- build.gradle
- genie-core/src/main/java/com/netflix/genie/core/services/impl/S3FileTransferImpl.java
- genie-web/src/main/java/com/netflix/genie/web/controllers/GenieExceptionMapper.java
- genie-web/src/main/java/com/netflix/genie/web/controllers/JobRestController.java
- genie-web/src/test/java/com/netflix/genie/web/controllers/GenieExceptionMapperUnitTests.java
- genie-web/src/test/java/com/netflix/genie/web/controllers/JobRestControllerUnitTests.java
Also upgrades Spring Platform to 2.0.4 and Spring Boot to 1.3.4.
> Added metrics for insights into job and error rates

- .travis.yml
- gradle/buildViaTravis.sh
Removed travis wait for build on Travis server and added --info flag to all gradlew commands. Also stopped using the installViaTravis script.
> Optimize build on travis servers

- genie-common/src/main/java/com/netflix/genie/common/dto/search/BaseSearchResult.java
- genie-common/src/main/java/com/netflix/genie/common/dto/search/JobSearchResult.java
- genie-common/src/main/java/com/netflix/genie/common/util/JsonDateDeserializer.java
- genie-common/src/main/java/com/netflix/genie/common/util/JsonDateSerializer.java
- genie-common/src/test/java/com/netflix/genie/common/dto/search/BaseSearchResultUnitTests.java
- genie-common/src/test/java/com/netflix/genie/common/dto/search/JobSearchResultUnitTests.java
- genie-common/src/test/java/com/netflix/genie/common/util/JsonDateSerializerUnitTests.java
- genie-core/src/main/java/com/netflix/genie/core/jpa/services/JpaJobSearchServiceImpl.java
- genie-web/src/main/java/com/netflix/genie/web/resources/writers/DefaultDirectoryWriter.java
- genie-web/src/test/java/com/netflix/genie/web/hateoas/assemblers/JobSearchResultResourceAssemblerUnitTests.java
- genie-web/src/test/java/com/netflix/genie/web/hateoas/resources/JobSearchResultResourceUnitTests.java
- genie-web/src/test/java/com/netflix/genie/web/resources/writers/DefaultDirectoryWriterUnitTests.java
Based on UI request/requirement.
Also changed the last modified time as an ISO8601 formatted string instead of just raw long for Job Output Directory listings in JSON.
> Add user to job search results fields

- gradle.properties
We had them pinned to release candidates.
> Update Spring Cloud Libraries to latest Release versions

- genie-client/src/main/python/pygenie/conf.py
Debug is a more appropriate log-level for these options.
> Switch conf logging from info to debug.

- genie-client/src/main/java/com/netflix/genie/client/ApplicationClient.java
- genie-client/src/main/java/com/netflix/genie/client/BaseGenieClient.java
- genie-client/src/main/java/com/netflix/genie/client/ClusterClient.java
- genie-client/src/main/java/com/netflix/genie/client/CommandClient.java
- genie-client/src/main/java/com/netflix/genie/client/JobClient.java
- genie-client/src/main/java/com/netflix/genie/client/exceptions/GenieClientException.java
- genie-client/src/main/java/com/netflix/genie/client/exceptions/GenieException.java
- genie-client/src/main/java/com/netflix/genie/client/exceptions/package-info.java
- genie-client/src/main/java/com/netflix/genie/client/interceptor/ResponseMappingInterceptor.java
- genie-client/src/test/java/com/netflix/genie/client/BaseGenieClientTests.java
- genie-client/src/test/java/com/netflix/genie/client/JobClientIntegrationTests.java
- genie-core/src/main/java/com/netflix/genie/core/jobs/JobConstants.java
Created a new GenieException inheriting from the IOException on the client side. This would allow client users to separate out the Genie Server and client specific issues from other generic IO problems.
> Refactored Exceptions on the Client side

- genie-client/src/main/python/pygenie/adapter/adapter.py
- genie-client/src/main/python/pygenie/adapter/genie_2.py
- genie-client/src/main/python/pygenie/adapter/genie_3.py
update output link for running job for Genie 3 in Python client
> update links and add SqoopJob in Python client

- genie-client/src/main/python/genie2/__init__.py
- genie-client/src/main/python/genie2/client/V2Api.py
- genie-client/src/main/python/genie2/client/__init__.py
- genie-client/src/main/python/genie2/client/api_client.py
- genie-client/src/main/python/genie2/client/wrapper.py
- genie-client/src/main/python/genie2/exception/__init__.py
- genie-client/src/main/python/genie2/exception/genie_exception.py
- genie-client/src/main/python/genie2/model/Application.py
- genie-client/src/main/python/genie2/model/Cluster.py
- genie-client/src/main/python/genie2/model/ClusterCriteria.py
- genie-client/src/main/python/genie2/model/Command.py
- genie-client/src/main/python/genie2/model/FileAttachment.py
- genie-client/src/main/python/genie2/model/Job.py
- genie-client/src/main/python/genie2/model/__init__.py
- genie-client/src/main/python/pygenie/conf.py
- genie-client/src/main/python/setup.py
- genie-client/src/main/python/tests/test_conf.py
Calling initialize to reload configs was causing issues when running in threads.
> don't use initialize to reload configs and re-add genie2 in Python client

- genie-web/src/main/resources/static/scripts/Application.js
- genie-web/src/main/resources/static/scripts/Cluster.js
- genie-web/src/main/resources/static/scripts/Command.js
- genie-web/src/main/resources/static/scripts/components/JobTableRow.js
- genie-web/src/main/resources/static/scripts/components/TableRow.js
> Add copy link button on all pages

- genie-web/src/main/resources/static/scripts/Job.js
> Add init and invalid status to jobs search dropdown 

- genie-core/src/main/java/com/netflix/genie/core/services/impl/JobCountServiceImpl.java
- genie-web/src/main/java/com/netflix/genie/web/tasks/job/JobMonitoringCoordinator.java
- genie-web/src/test/java/com/netflix/genie/web/controllers/JobRestControllerIntegrationTests.java
- genie-web/src/test/resources/application-ci.yml
Also add more testing debug information for debugging any Travis issues
> Remove unnecessary synchronized statements

- genie-web/src/main/resources/static/scripts/Application.js
- genie-web/src/main/resources/static/scripts/Cluster.js
- genie-web/src/main/resources/static/scripts/Command.js
- genie-web/src/main/resources/static/scripts/Job.js
- genie-web/src/main/resources/static/scripts/Main.js
- genie-web/src/main/resources/static/scripts/OutputDirectory.js
- genie-web/src/main/resources/static/scripts/Page.js
- genie-web/src/main/resources/static/scripts/components/ApplicationDetails.js
- genie-web/src/main/resources/static/scripts/components/CommandDetails.js
- genie-web/src/main/resources/static/scripts/components/JobTableRow.js
- genie-web/src/main/resources/static/scripts/components/SearchForm.js
- genie-web/src/main/resources/static/scripts/utils.js
* Multiselect option to search jobs by status
* UTC format for all date time fields
part of #164
> Job status search + UTC date formatting changes

- genie-core/src/main/java/com/netflix/genie/core/jpa/services/JpaJobPersistenceServiceImpl.java
- genie-core/src/main/java/com/netflix/genie/core/services/JobPersistenceService.java
- genie-web/build.gradle
- genie-web/src/main/java/com/netflix/genie/web/security/oauth2/pingfederate/PingFederateConfig.java
- genie-web/src/main/java/com/netflix/genie/web/security/oauth2/pingfederate/PingFederateTokenServices.java
- genie-web/src/main/java/com/netflix/genie/web/security/saml/SAMLUserDetailsServiceImpl.java
- genie-web/src/main/java/com/netflix/genie/web/tasks/job/JobCompletionHandler.java
- genie-web/src/test/java/com/netflix/genie/web/security/oauth2/pingfederate/PingFederateTokenServicesUnitTests.java
- genie-web/src/test/java/com/netflix/genie/web/security/saml/SAMLUserDetailsServiceImplUnitTests.java
- gradle.properties
This PR adds more metrics for tracking job completion and security API calls for debugging and alerting.
> Adding metrics for security and job completion

- genie-web/package.json
- genie-web/src/main/resources/static/scripts/OutputDirectory.js
> Correctly determine size of files in Directory output viewer 

- genie-client/src/test/java/com/netflix/genie/client/GenieClientsIntegrationTestsBase.java
- genie-core/src/main/java/com/netflix/genie/core/services/impl/CacheGenieFileTransferService.java
- genie-core/src/test/groovy/com/netflix/genie/core/services/impl/CacheGenieFileTransferServiceSpec.groovy
- genie-web/src/main/resources/application.yml
- genie-web/src/test/java/com/netflix/genie/web/controllers/JobRestControllerIntegrationTests.java
- genie-web/src/test/java/com/netflix/genie/web/controllers/RestControllerIntegrationTestsBase.java
- genie-web/src/test/java/com/netflix/genie/web/security/oauth2/pingfederate/PingFederateConfigIntegrationTests.java
- genie-web/src/test/java/com/netflix/genie/web/security/x509/X509ConfigIntegrationTests.java
- genie-web/src/test/resources/application-ci.yml
- genie-web/src/test/resources/application-integration.yml
Also modified genie.file.cache.location to correctly point to /tmp.
> Removed @DirtiesContext so as to not restarting the application across tests

- genie-web/src/main/java/com/netflix/genie/web/controllers/JobRestController.java
This error only happened the first time the request is made with a new session or stale one. Issue was that while forwarding the request to a different node, the session cookie was not forwarded.
> Fixed issue where the job output request was responding back with a 401 error

- genie-web/package.json
- genie-web/src/main/resources/static/scripts/Cluster.js
- genie-web/src/main/resources/static/scripts/Job.js
- genie-web/src/main/resources/static/scripts/Main.js
- genie-web/src/main/resources/static/scripts/OutputDirectory.js
- genie-web/src/main/resources/static/scripts/components/JobDetails.js
- genie-web/src/main/resources/static/scripts/components/JobTableRow.js
- genie-web/src/main/resources/static/scripts/components/SearchForm.js
- genie-web/src/main/resources/static/scripts/components/SiteHeader.js
- genie-web/src/main/resources/static/scripts/components/TableRow.js
- genie-web/src/main/resources/static/scripts/utils.js
- genie-web/src/main/resources/static/styles/genie.css
* A confirm modal pop up
* Links to search results and main genie site from output directory page
part of #164
> A modal confirmation pop up before sending job kill request

- genie-web/src/main/resources/static/scripts/Job.js
- genie-web/src/main/resources/static/scripts/Main.js
- genie-web/src/main/resources/static/scripts/components/AuthCheck.js
- genie-web/src/main/resources/static/scripts/components/JobDetails.js
- Periodically check for a valid auth session. 
- Automatic refresh of stale auth session tokens
part of #164
> Valid auth session checker

- genie-web/src/main/resources/static/scripts/components/JobDetails.js
> Fix typo on the kill job request button

- genie-web/src/main/resources/static/scripts/components/CommandDetails.js
- genie-web/src/main/resources/static/scripts/components/JobDetails.js
> Fetch active cluster details

- genie-web/src/main/resources/static/scripts/OutputDirectory.js
- genie-web/src/main/resources/static/scripts/Page.js
- genie-web/src/main/resources/static/scripts/components/AuthCheck.js
- genie-web/src/main/resources/static/scripts/components/Error.js
- genie-web/src/main/resources/static/scripts/components/InfoTable.js
- genie-web/src/main/resources/static/scripts/components/JobDetails.js
- genie-web/src/main/resources/static/scripts/components/JobTableRow.js
- genie-web/src/main/resources/static/scripts/components/Loading.js
- genie-web/src/main/resources/static/scripts/components/NoSearchResult.js
- genie-web/src/main/resources/static/scripts/components/Pagination.js
- genie-web/src/main/resources/static/scripts/components/SearchForm.js
- genie-web/src/main/resources/static/styles/genie.css
> Better error handling and display cluster/application/command links on jobs page

- genie-core/src/main/java/com/netflix/genie/core/jobs/JobConstants.java
- genie-core/src/main/java/com/netflix/genie/core/jobs/workflow/impl/JobKickoffTask.java
- genie-core/src/main/java/com/netflix/genie/core/jobs/workflow/impl/JobTask.java
- genie-core/src/main/java/com/netflix/genie/core/jpa/services/JpaJobSearchServiceImpl.java
- genie-core/src/test/java/com/netflix/genie/core/jpa/services/JpaJobSearchServiceImplUnitTests.java
- genie-web/src/main/java/com/netflix/genie/web/tasks/job/JobCompletionService.java
- genie-web/src/test/resources/com/netflix/genie/web/controllers/JobRestControllerIntegrationTests/linux-runsh.txt
- genie-web/src/test/resources/com/netflix/genie/web/controllers/JobRestControllerIntegrationTests/non-linux-runsh.txt
GetApplications for a job returns an empty list instead of NotFoundException. Emails are more detailed.Archival and Cleanup of job directories only happens if the job runs. Fixed an edge case where job submission failed if user/group specified were the same in the jobrequest.Emails upon job completion are more detailed.
Added start and end time to genie log file for debugging.
> Fixes in email, Job.GetApplications, Job cleanup and archiving and Job submission with same user/group.

- build.gradle
- genie-client/build.gradle
- genie-client/src/main/java/com/netflix/genie/client/BaseGenieClient.java
- genie-client/src/main/java/com/netflix/genie/client/JobClient.java
- genie-client/src/main/java/com/netflix/genie/client/configs/GenieNetworkConfiguration.java
- gradle.properties
Can be disabled by setting a field in the GenieNetworkConfiguration. Upgrade retrofit and okhttp libraries to get all bug fixes
> Make retrying on connection failures on by default

- .travis.yml
- build.gradle
- genie-app/build.gradle
- genie-app/src/main/docker/Dockerfile
- gradle/buildViaTravis.sh
Will publish a docker image for genie-app to the travis-ci builds.
> Publish a docker image for genie-app

- README.md
- genie-app/build.gradle
- genie-core/src/main/java/com/netflix/genie/core/services/impl/JobCoordinatorServiceImpl.java
- genie-demo/build.gradle
- genie-demo/src/main/docker/apache/Dockerfile
- genie-demo/src/main/docker/apache/files/applications/hadoop/2.7.1/setup.sh
- genie-demo/src/main/docker/apache/files/clusters/yarn/2.7.1/prod/conf/core-site.xml
- genie-demo/src/main/docker/apache/files/clusters/yarn/2.7.1/prod/conf/mapred-site.xml
- genie-demo/src/main/docker/apache/files/clusters/yarn/2.7.1/prod/conf/yarn-site.xml
- genie-demo/src/main/docker/apache/files/clusters/yarn/2.7.1/test/conf/core-site.xml
- genie-demo/src/main/docker/apache/files/clusters/yarn/2.7.1/test/conf/mapred-site.xml
- genie-demo/src/main/docker/apache/files/clusters/yarn/2.7.1/test/conf/yarn-site.xml
- genie-demo/src/main/docker/client/Dockerfile
- genie-demo/src/main/docker/client/example/applications/hadoop271.yml
- genie-demo/src/main/docker/client/example/clusters/prod.yml
- genie-demo/src/main/docker/client/example/clusters/test.yml
- genie-demo/src/main/docker/client/example/commands/hadoop271.yml
- genie-demo/src/main/docker/client/example/commands/hdfs271.yml
- genie-demo/src/main/docker/client/example/commands/yarn271.yml
- genie-demo/src/main/docker/client/example/init_demo.py
- genie-demo/src/main/docker/client/example/run_hadoop_job.py
- genie-demo/src/main/docker/client/example/run_hdfs_job.py
- genie-demo/src/main/docker/client/example/run_yarn_job.py
- genie-demo/src/main/docker/docker-compose.yml
- settings.gradle
Able to run demo without any installation using just gradle and docker.
> Initial version of a Genie 3 demo built on Docker Compose.

- genie-web/src/main/resources/static/scripts/components/JobDetails.js
> Add more command info on Job details section

- genie-client/src/main/python/setup.py
```<bad joke>This PR needs a +1</bad joke>```
> Bump setup.py version.

- genie-core/src/main/java/com/netflix/genie/core/jobs/workflow/impl/JobKickoffTask.java
Before running the script, added check to see if it is used by any other programs. We check for 3 times and even after that if it is being used by another program, we go ahead and try running it, instead of failing.
> Resolved issue where a genie job errors out  with meesage 'Text file busy' when running the run script.

- genie-core/src/main/java/com/netflix/genie/core/properties/HealthProperties.java
- genie-core/src/main/java/com/netflix/genie/core/services/impl/GenieFileTransferService.java
- genie-web/src/main/java/com/netflix/genie/web/configs/PropertiesConfig.java
- genie-web/src/main/java/com/netflix/genie/web/health/GenieCpuHealthIndicator.java
- genie-web/src/main/java/com/netflix/genie/web/health/GenieMemoryHealthIndicator.java
- genie-web/src/main/resources/application.yml
- genie-web/src/test/groovy/com/netflix/genie/web/health/GenieCpuHealthIndicatorSpec.groovy
- genie-web/src/test/java/com/netflix/genie/web/health/GenieHealthIndicatorUnitTests.java
- genie-web/src/test/java/com/netflix/genie/web/health/GenieMemoryHealthIndicatorUnitTests.java
- genie-web/src/test/resources/application-ci.yml
- genie-web/src/test/resources/application-integration.yml
2. Corrected the error message when a URI path is invalid.
> Add a health indicator for the CPU usage

- genie-web/src/docs/asciidoc/api/clusters/_getCluster.adoc
- genie-web/src/docs/asciidoc/api/commands/_getCommand.adoc
- genie-web/src/docs/asciidoc/index.adoc
Fix grammar errors
Fix wrong link for demo documentation from REST api documentation
> Documentation clean up

- genie-demo/src/docs/asciidoc/docinfo.html
- genie-demo/src/docs/asciidoc/index.adoc
- genie-docs/build.gradle
- genie-docs/src/docs/asciidoc/_installation.adoc
- genie-docs/src/docs/asciidoc/_properties.adoc
- genie-docs/src/docs/asciidoc/concepts/_concepts.adoc
- genie-docs/src/docs/asciidoc/concepts/_dataModel.adoc
- genie-docs/src/docs/asciidoc/concepts/_howItWorks.adoc
- genie-docs/src/docs/asciidoc/concepts/_netflixDeployment.adoc
- genie-docs/src/docs/asciidoc/concepts/_netflixExample.adoc
- genie-docs/src/docs/asciidoc/concepts/_security.adoc
- genie-docs/src/docs/asciidoc/docinfo.html
- genie-docs/src/docs/asciidoc/index.adoc
- genie-web/src/docs/asciidoc/docinfo.html
- genie-web/src/docs/asciidoc/index.adoc
> Reference documentation for 3.0.0

- genie-core/src/main/java/com/netflix/genie/core/jpa/repositories/JpaJobExecutionRepository.java
- genie-core/src/main/java/com/netflix/genie/core/jpa/repositories/JpaJobMetadataRepository.java
- genie-core/src/main/java/com/netflix/genie/core/jpa/repositories/JpaJobRepository.java
- genie-core/src/main/java/com/netflix/genie/core/jpa/repositories/JpaJobRequestRepository.java
- genie-core/src/main/java/com/netflix/genie/core/jpa/services/JpaJobPersistenceServiceImpl.java
- genie-core/src/test/java/com/netflix/genie/GenieCoreTestApplication.java
Cherry pick of #493 from 3.0.x
> Modify job cleanup query to limit amount of data returned via id projection

- genie-web/src/main/resources/application.yml
Avoid situation described in #529 with default parameters.
> Increase default thread pool sizes

- build.gradle
- gradle.properties
Unpin bouncycastle as well by upgrading to OpenSAML 2.6.4
> Upgrade to Spring Boot 1.5.4

- genie-common/src/main/java/com/netflix/genie/common/dto/ClusterCriteria.java
- genie-common/src/main/java/com/netflix/genie/common/dto/JobRequest.java
- genie-core/src/main/java/com/netflix/genie/core/util/MetricsConstants.java
- genie-web/src/main/java/com/netflix/genie/web/controllers/GenieExceptionMapper.java
- genie-web/src/test/java/com/netflix/genie/web/controllers/GenieExceptionMapperUnitTests.java
- genie-web/src/test/java/com/netflix/genie/web/controllers/JobRestControllerIntegrationTests.java
- genie-web/src/test/java/com/netflix/genie/web/controllers/Snippets.java
> Reject jobs requests with precondition failed when no valid (non-blank) Cluster Criteria or Command Criteria found

- .gitignore
- genie-core/src/main/java/com/netflix/genie/core/services/impl/LocalFileTransferImpl.java
- genie-web/src/main/java/com/netflix/genie/web/services/loadbalancers/script/ScriptLoadBalancer.java
- genie-web/src/test/groovy/com/netflix/genie/web/services/loadbalancers/script/ScriptLoadBalancerSpec.groovy
Instead of old java.io.
Fix consistency of script handling for directories and files to be downloaded.
> Fix script load balancer and local file transfer to use java.nio

- genie-core/src/main/java/com/netflix/genie/core/services/impl/S3FileTransferImpl.java
- genie-core/src/test/java/com/netflix/genie/core/services/impl/S3FileTransferImplUnitTests.java
Refactor S3FileTransferImpl to use AmazonS3URI to parse S3 paths.
Plus perform additional path validation as per:
- http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html#object-keys
- http://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html#bucketnamingrules
Revamp the tests to cover the new code and logic.
> Improvements to S3FileTransfer and tests

- .travis.yml
- genie-core/src/test/java/com/netflix/genie/core/jobs/JobLauncherUnitTests.java
- genie-core/src/test/java/com/netflix/genie/core/services/impl/JobCoordinatorServiceImplUnitTests.java
- genie-core/src/test/java/com/netflix/genie/core/services/impl/S3FileTransferImplUnitTests.java
- genie-web/build.gradle
- genie-web/src/main/java/com/netflix/genie/web/tasks/job/JobCompletionService.java
- genie-web/src/test/groovy/com/netflix/genie/web/tasks/job/JobCompletionServiceSpec.groovy
- genie-web/src/test/java/com/netflix/genie/web/configs/aws/AwsMvcConfigUnitTests.java
- genie-web/src/test/java/com/netflix/genie/web/services/impl/HttpFileTransferImplTest.java
- genie-web/src/test/java/com/netflix/genie/web/tasks/job/JobMonitoringCoordinatorUnitTests.java
- genie-web/src/test/java/com/netflix/genie/web/tasks/leader/DatabaseCleanupTaskUnitTests.java
- Improve NPM Build
- Add additional caching to travis to hopefully speed up build
> Fix tagging for final job status on metrics

- .travis.yml
- genie-core/src/main/java/com/netflix/genie/core/util/MetricsUtils.java
- genie-web/src/main/java/com/netflix/genie/web/tasks/job/JobCompletionService.java
- Remove `.gradle/caches/*/fileHashes/fileHashes.bin` and `.gradle/caches/*/fileHashes/fileHashes.lock` from travis caching
- Cleaned up some warnings in editor for source code while looking through metrics to fix dashboards
> Some metrics code cleanup

- genie-web/src/main/java/com/netflix/genie/web/controllers/ControllerUtils.java
- genie-web/src/main/java/com/netflix/genie/web/controllers/JobRestController.java
- genie-web/src/main/java/com/netflix/genie/web/services/impl/HttpFileTransferImpl.java
- genie-web/src/test/java/com/netflix/genie/web/controllers/ControllerUtilsUnitTests.java
- genie-web/src/test/java/com/netflix/genie/web/controllers/JobRestControllerUnitTests.java
> Templatize RestTemplate usage for Job API forwarding

- genie-core/src/main/java/com/netflix/genie/core/properties/DataServiceRetryProperties.java
- genie-core/src/main/java/com/netflix/genie/core/properties/HealthProperties.java
- genie-core/src/main/java/com/netflix/genie/core/properties/JobsCleanupProperties.java
- genie-core/src/main/java/com/netflix/genie/core/properties/JobsForwardingProperties.java
- genie-core/src/main/java/com/netflix/genie/core/properties/JobsLocationsProperties.java
- genie-core/src/main/java/com/netflix/genie/core/properties/JobsMaxProperties.java
- genie-core/src/main/java/com/netflix/genie/core/properties/JobsMemoryProperties.java
- genie-core/src/main/java/com/netflix/genie/core/properties/JobsProperties.java
- genie-core/src/main/java/com/netflix/genie/core/properties/JobsUsersActiveLimitProperties.java
- genie-core/src/main/java/com/netflix/genie/core/properties/JobsUsersProperties.java
- genie-core/src/main/java/com/netflix/genie/core/properties/S3FileTransferProperties.java
- genie-web/src/main/java/com/netflix/genie/web/properties/ClusterCheckerProperties.java
- genie-web/src/main/java/com/netflix/genie/web/properties/DatabaseCleanupProperties.java
- genie-web/src/main/java/com/netflix/genie/web/properties/DiskCleanupProperties.java
- genie-web/src/main/java/com/netflix/genie/web/properties/ZookeeperProperties.java
- genie-web/src/main/java/com/netflix/genie/web/security/saml/SAMLProperties.java
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.5-Release-Notes#configurationproperties-validation
> Add @Validated to @ConfigurationProperties beans to support JSR-303 annotations

- genie-web/src/main/resources/static/index.html
This likely won't fix the current `laquo` issue, wise to do in the meantime.
> Explicitly set the lang

- genie-web/src/test/java/com/netflix/genie/web/controllers/ApplicationRestControllerIntegrationTests.java
- genie-web/src/test/java/com/netflix/genie/web/controllers/ClusterRestControllerIntegrationTests.java
- genie-web/src/test/java/com/netflix/genie/web/controllers/CommandRestControllerIntegrationTests.java
- genie-web/src/test/java/com/netflix/genie/web/controllers/JobRestControllerIntegrationTests.java
ensure starting fresh for each controller integration test
> Add pre-cleanup for database tables in integration tests

- genie-web/src/test/java/com/netflix/genie/web/controllers/ApplicationRestControllerIntegrationTests.java
- genie-web/src/test/java/com/netflix/genie/web/controllers/ClusterRestControllerIntegrationTests.java
- genie-web/src/test/java/com/netflix/genie/web/controllers/CommandRestControllerIntegrationTests.java
- genie-web/src/test/java/com/netflix/genie/web/controllers/JobRestControllerIntegrationTests.java
> Add pre-cleanup for database tables to ensure starting fresh for each controller integration test

- genie-docs/src/docs/asciidoc/_metrics.adoc
- genie-web/src/main/java/com/netflix/genie/web/aspect/HealthCheckMetricsAspect.java
- genie-web/src/main/resources/application.yml
- genie-web/src/test/groovy/com/netflix/genie/web/aspect/HealthCheckMetricsAspectSpec.groovy
Publish timing and failure metrics related to healtcheck. 
Disable two non-essential healtchchecks.
> Health metrics and disable non-essentials checks

- genie-client/src/main/java/com/netflix/genie/client/security/oauth2/impl/OAuth2SecurityInterceptor.java
- genie-core/src/main/java/com/netflix/genie/core/jobs/workflow/impl/JobKickoffTask.java
- genie-core/src/main/java/com/netflix/genie/core/services/impl/FileSystemAttachmentService.java
- genie-core/src/main/java/com/netflix/genie/core/services/impl/GenieFileTransferService.java
- genie-core/src/main/java/com/netflix/genie/core/services/impl/MailServiceImpl.java
- genie-core/src/main/java/com/netflix/genie/core/services/impl/S3FileTransferImpl.java
- genie-docs/src/docs/asciidoc/_metrics.adoc
- genie-web/src/main/java/com/netflix/genie/web/aspect/HealthCheckMetricsAspect.java
- genie-web/src/main/java/com/netflix/genie/web/tasks/job/JobCompletionService.java
- genie-web/src/main/resources/application.yml
- genie-web/src/test/groovy/com/netflix/genie/web/aspect/HealthCheckMetricsAspectSpec.groovy
* https://github.com/Netflix/genie/pull/622 SLF4J 
* https://github.com/Netflix/genie/pull/633 Missing exception traces
* https://github.com/Netflix/genie/pull/632 Healtchecks
> Cherry-picks from master

- genie-web/src/main/java/com/netflix/genie/web/tasks/job/JobCompletionService.java
Cherry-pick of https://github.com/Netflix/genie/pull/637
> Log exception trace when failing to create job files archive

- genie-core/src/main/java/com/netflix/genie/core/jpa/entities/CommonFieldsEntity.java
- genie-core/src/main/java/com/netflix/genie/core/jpa/entities/JobRequestEntity.java
- genie-ddl/src/main/sql/postgresql/schema.postgresql.sql
Address issues encountered as part of investigating https://github.com/Netflix/genie/issues/636
> PostgreSQL fixies

- genie-common/src/main/java/com/netflix/genie/common/dto/Job.java
- genie-common/src/main/java/com/netflix/genie/common/dto/JobRequest.java
- travis/buildViaTravis.sh
Also add javadoc task to pull request build to prevent surprises once merge occurs
Build broke for #651 due to lack of javadoc target in PR builds
> Fix javadoc for #651

- build.gradle
- genie-core/build.gradle
- genie-web/src/test/java/com/netflix/genie/web/controllers/Snippets.java
Improve compilation times by combining meta-model generation into the main java build
Improve documentation by explicitly declaring JSON types
> Improve documentation and compiliation

- build.gradle
- genie-proto/build.gradle
- genie-web/build.gradle
- genie-web/src/main/java/com/netflix/genie/web/jpa/services/JpaBaseService.java
- genie-web/src/main/java/com/netflix/genie/web/jpa/services/JpaFileServiceImpl.java
- genie-web/src/main/java/com/netflix/genie/web/jpa/services/JpaTagServiceImpl.java
- genie-web/src/main/java/com/netflix/genie/web/services/FileService.java
- genie-web/src/main/java/com/netflix/genie/web/services/TagService.java
- genie-web/src/test/java/com/netflix/genie/web/controllers/ApplicationRestControllerIntegrationTests.java
- genie-web/src/test/java/com/netflix/genie/web/controllers/ClusterRestControllerIntegrationTests.java
- genie-web/src/test/java/com/netflix/genie/web/controllers/CommandRestControllerIntegrationTests.java
> Build fixes for Javadoc and JaCoCo + cherry-pick #671

- genie-docs/src/docs/asciidoc/_properties.adoc
- genie-web/src/main/java/com/netflix/genie/web/properties/DatabaseCleanupProperties.java
- genie-web/src/main/java/com/netflix/genie/web/tasks/leader/DatabaseCleanupTask.java
- genie-web/src/main/resources/static/scripts/components/ApplicationDetails.js
- genie-web/src/main/resources/static/scripts/components/ClusterDetails.js
- genie-web/src/main/resources/static/scripts/components/CommandDetails.js
- genie-web/src/main/resources/static/scripts/utils.js
- genie-web/src/test/java/com/netflix/genie/web/properties/DatabaseCleanupPropertiesUnitTests.java
- genie-web/src/test/java/com/netflix/genie/web/tasks/leader/DatabaseCleanupTaskUnitTests.java
> Cherry-picks from 3.3.x

- genie-web/npm-shrinkwrap.json
- genie-web/package.json
* Primarily to overcome security vulnerabilities found in 2.x series.
> Update jquery dependency to 3.3.1

- genie-web/npm-shrinkwrap.json
- genie-web/package.json
- genie-web/src/main/java/com/netflix/genie/web/jpa/repositories/JpaClusterRepository.java
- genie-web/src/main/java/com/netflix/genie/web/jpa/repositories/JpaFileRepository.java
- genie-web/src/main/java/com/netflix/genie/web/jpa/repositories/JpaTagRepository.java
- genie-web/src/main/java/com/netflix/genie/web/jpa/services/JpaClusterServiceImpl.java
- genie-web/src/main/java/com/netflix/genie/web/jpa/services/JpaFileServiceImpl.java
- genie-web/src/main/java/com/netflix/genie/web/jpa/services/JpaTagServiceImpl.java
- genie-web/src/main/java/com/netflix/genie/web/services/ClusterService.java
- genie-web/src/main/java/com/netflix/genie/web/services/FileService.java
- genie-web/src/main/java/com/netflix/genie/web/services/TagService.java
- genie-web/src/main/java/com/netflix/genie/web/tasks/leader/DatabaseCleanupTask.java
- genie-web/src/test/java/com/netflix/genie/web/jpa/services/JpaClusterServiceImplIntegrationTests.java
- genie-web/src/test/java/com/netflix/genie/web/jpa/services/JpaFileServiceImplIntegrationTest.java
- genie-web/src/test/java/com/netflix/genie/web/jpa/services/JpaTagServiceImplIntegrationTest.java
- genie-web/src/test/java/com/netflix/genie/web/tasks/leader/DatabaseCleanupTaskUnitTests.java
Cherry picks include #680 and #682.
#680 CP had slight modifications for improvements in Hibernate 5.2 and queries available.
> Cherry Pick fixes from 3.3.x

- genie-client/src/main/java/com/netflix/genie/client/JobClient.java
- genie-client/src/main/java/com/netflix/genie/client/apis/JobService.java
- genie-client/src/test/java/com/netflix/genie/client/JobClientIntegrationTests.java
> Add missing job metadata API to client

- gradle.properties
Primarily to pick up security vulnerability fixes
> Upgrade to Spring Boot 1.5.10 and associated release trains

- build.gradle
> Cherry-pick #691

- genie-web/src/test/java/com/netflix/genie/web/controllers/ApplicationRestControllerIntegrationTests.java
- genie-web/src/test/java/com/netflix/genie/web/controllers/ClusterRestControllerIntegrationTests.java
- genie-web/src/test/java/com/netflix/genie/web/controllers/CommandRestControllerIntegrationTests.java
- genie-web/src/test/java/com/netflix/genie/web/controllers/JobRestControllerIntegrationTests.java
- genie-web/src/test/java/com/netflix/genie/web/controllers/RestControllerIntegrationTestsBase.java
- gradle.properties
Clean up common snippet pieces
> Add Wiremock stubbing back into Rest docs generation

- build.gradle
- genie-common/src/main/java/com/netflix/genie/common/dto/v4/Criterion.java
- genie-common/src/main/java/com/netflix/genie/common/dto/v4/JobRequest.java
- gradle.properties
> Upgrade to Spring Boot 2.0.0 Release

- genie-docs/src/docs/asciidoc/_properties.adoc
- genie-web/src/main/java/com/netflix/genie/web/properties/ExponentialBackOffTriggerProperties.java
- genie-web/src/main/java/com/netflix/genie/web/properties/JobsProperties.java
- genie-web/src/main/java/com/netflix/genie/web/tasks/job/JobMonitor.java
- genie-web/src/main/java/com/netflix/genie/web/util/ExponentialBackOffTrigger.java
- genie-web/src/test/groovy/com/netflix/genie/web/util/ExponentialBackOffTriggerSpec.groovy
- genie-web/src/test/java/com/netflix/genie/web/controllers/JobRestControllerIntegrationTests.java
- genie-web/src/test/java/com/netflix/genie/web/properties/ExponentialBackOffTriggerPropertiesUnitTest.java
- genie-web/src/test/java/com/netflix/genie/web/tasks/job/JobMonitorUnitTests.java
- genie-web/src/test/java/com/netflix/genie/web/tasks/job/JobMonitoringCoordinatorUnitTests.java
This is a cherry-pick of https://github.com/Netflix/genie/pull/733
> Exponential backoff for for job completion check (#733 cherry pick)

- build.gradle
- gradle.properties
Various dependency upgrades to latest versions for libraries we're using
> Upgrade dependencies

- build.gradle
- genie-web/src/main/java/com/netflix/genie/web/configs/MvcConfig.java
- genie-web/src/main/java/com/netflix/genie/web/security/SecurityConfig.java
- gradle.properties
Also changes to remove conflicts with internal boot auto configurations from runtime team from some our beans and security configurations discovered during debugging session today
> Upgrade to Spring Boot 2.0.3

- genie-security/build.gradle
- genie-security/src/main/java/com/netflix/genie/security/configs/HttpSessionConfig.java
- genie-security/src/main/java/com/netflix/genie/security/configs/RedisConfig.java
- genie-security/src/main/java/com/netflix/genie/security/configs/package-info.java
- genie-security/src/test/java/com/netflix/genie/security/configs/HttpSessionConfigUnitTests.java
- genie-security/src/test/java/com/netflix/genie/security/configs/package-info.java
- genie-ui/src/main/java/com/netflix/genie/ui/controllers/UIController.java
- genie-ui/src/main/java/com/netflix/genie/ui/controllers/UserRestController.java
- genie-ui/src/main/web/scripts/Main.js
- genie-ui/src/test/groovy/com/netflix/genie/ui/controllers/UserRestControllerSpec.groovy
- genie-ui/src/test/java/com/netflix/genie/ui/controllers/UIControllerUnitTests.java
- genie-web/build.gradle
- Remove spring session from default `genie-web` build as internally an optimized implementation is available
- Remove username cookie that could cause invalid cookie errors in Tomcat for more API based solution for UI
> Miscellaneous fixes based on internal integration testing

- genie-web/src/main/java/com/netflix/genie/web/configs/LeadershipConfig.java
- genie-web/src/main/java/com/netflix/genie/web/configs/RedisConfig.java
- genie-web/src/main/java/com/netflix/genie/web/configs/ZookeeperConfig.java
- genie-web/src/main/java/com/netflix/genie/web/security/SecurityConditions.java
- genie-web/src/main/java/com/netflix/genie/web/security/oauth2/OAuth2Config.java
- genie-web/src/main/java/com/netflix/genie/web/security/oauth2/pingfederate/PingFederateSecurityConditions.java
- genie-web/src/main/java/com/netflix/genie/web/security/saml/SAMLConfig.java
- genie-web/src/main/java/com/netflix/genie/web/security/saml/SAMLProperties.java
- genie-web/src/main/java/com/netflix/genie/web/security/saml/SAMLUserDetailsServiceImpl.java
- genie-web/src/main/java/com/netflix/genie/web/security/x509/X509Config.java
- genie-web/src/main/java/com/netflix/genie/web/tasks/leader/DatabaseCleanupTask.java
- genie-web/src/main/java/com/netflix/genie/web/tasks/node/DiskCleanupTask.java
Also enforce true for all `enabled` feature flags
> Fix incorrect property in Disk Cleanup task conditional

- genie-web/src/main/java/com/netflix/genie/web/controllers/JobRestController.java
- genie-web/src/main/java/com/netflix/genie/web/jpa/services/JpaJobSearchServiceImpl.java
- genie-web/src/main/java/com/netflix/genie/web/services/JobSearchService.java
- genie-web/src/test/java/com/netflix/genie/web/controllers/JobRestControllerUnitTests.java
First draft for forwarding v4 job kill request to the right genie box. No tests added yet. Trying to get an early feedback on design.
> Handle v4 job kill request forwarding

- genie-agent/src/main/java/com/netflix/genie/agent/cli/ExecCommand.java
- genie-agent/src/main/java/com/netflix/genie/agent/cli/GenieAgentRunnner.java
- genie-agent/src/main/java/com/netflix/genie/agent/cli/UserConsole.java
- genie-agent/src/main/java/com/netflix/genie/agent/execution/ExecutionContext.java
- genie-agent/src/main/java/com/netflix/genie/agent/execution/ExecutionContextImpl.java
- genie-agent/src/main/java/com/netflix/genie/agent/execution/services/KillService.java
- genie-agent/src/main/java/com/netflix/genie/agent/execution/services/LaunchJobService.java
- genie-agent/src/main/java/com/netflix/genie/agent/execution/services/impl/KillServiceImpl.java
- genie-agent/src/main/java/com/netflix/genie/agent/execution/services/impl/LaunchJobServiceImpl.java
- genie-agent/src/main/java/com/netflix/genie/agent/execution/services/impl/grpc/GRpcAgentJobKillServiceImpl.java
- genie-agent/src/main/java/com/netflix/genie/agent/execution/statemachine/actions/CleanupJobAction.java
- genie-agent/src/main/java/com/netflix/genie/agent/execution/statemachine/actions/LaunchJobAction.java
- genie-agent/src/main/java/com/netflix/genie/agent/execution/statemachine/actions/MonitorJobAction.java
- genie-agent/src/test/groovy/com/netflix/genie/agent/cli/ExecCommandSpec.groovy
- genie-agent/src/test/groovy/com/netflix/genie/agent/cli/UserConsoleSpec.groovy
- genie-agent/src/test/groovy/com/netflix/genie/agent/execution/ExecutionContextImplSpec.groovy
- genie-agent/src/test/groovy/com/netflix/genie/agent/execution/services/KillServiceImplSpec.groovy
- genie-agent/src/test/groovy/com/netflix/genie/agent/execution/services/impl/LaunchJobServiceImplSpec.groovy
- genie-agent/src/test/groovy/com/netflix/genie/agent/execution/services/impl/grpc/GRpcAgentJobKillServiceImplSpec.groovy
- genie-agent/src/test/groovy/com/netflix/genie/agent/execution/statemachine/actions/CleanupJobActionSpec.groovy
- genie-agent/src/test/groovy/com/netflix/genie/agent/execution/statemachine/actions/LaunchJobActionSpec.groovy
- genie-agent/src/test/groovy/com/netflix/genie/agent/execution/statemachine/actions/MonitorJobActionSpec.groovy
* Implement `KillService` and do some refactoring to use it. 
* Update signal handling to make use of `KillService`.
* Update `LaunchJobService` implementation, simplify state actions.
* Improve error messages in console
> Agent KillService, JobLaunchService, user console error logging

- genie-web/src/main/resources/static/scripts/utils.js
* moment assignment to the windows object is not needed
> Remove test UI code

- genie-ui/npm-shrinkwrap.json
- genie-ui/package.json
- genie-ui/src/main/web/scripts/Application.js
- genie-ui/src/main/web/scripts/Cluster.js
- genie-ui/src/main/web/scripts/Command.js
- genie-ui/src/main/web/scripts/Job.js
- genie-ui/src/main/web/scripts/Main.js
- genie-ui/src/main/web/scripts/Page.js
- genie-ui/src/main/web/scripts/components/ApplicationDetails.js
- genie-ui/src/main/web/scripts/components/ClusterDetails.js
- genie-ui/src/main/web/scripts/components/CommandDetails.js
- genie-ui/src/main/web/scripts/components/JobDetails.js
- genie-ui/src/main/web/scripts/components/JobTableRow.js
- genie-ui/src/main/web/scripts/components/SearchForm.js
- genie-ui/src/main/web/scripts/components/TableBody.js
- genie-ui/src/main/web/scripts/components/TableRow.js
- genie-ui/src/main/web/scripts/components/ToggleTimeZone.js
- genie-ui/src/main/web/scripts/utils.js
- genie-ui/src/main/web/styles/genie.css
- genie-ui/webpack.config.js
Cherry picks all commits from #840 into master.
> UI Improvements

- genie-web/src/main/java/com/netflix/genie/web/services/impl/JobDirectoryServerServiceImpl.java
- genie-web/src/test/groovy/com/netflix/genie/web/services/impl/JobDirectoryServerServiceImplSpec.groovy
If a job wasn't archived it will now return a 404 instead of a 500.
Also all error cases are written to the log to help with debugging.
> Improve the log and error returns for various conditions in the job directory service

- genie-ui/package.json
* Fix https://github.com/Netflix/genie/network/alert/genie-ui/package.json/npm/open
* Bump npm to the latest stable version
* https://github.com/npm/cli/releases/tag/v6.13.4
> Bump npm version to avoid vulnerabilities

- build.gradle
- genie-app/build.gradle
- genie-common-internal/src/main/java/com/netflix/genie/common/internal/aws/s3/S3ProtocolResolver.java
Hopefully fixes publishing bug
Switch to Plugins block
> Upgrade Netflix OSS Plugin to 8.4.4

- genie-web/src/main/java/com/netflix/genie/web/tasks/job/JobCompletionService.java
A race condition was possible where two (or more) threads would be executing JobCompletionService::handleJobCompletion.
The threads would disturb eachother by deleting files and archiving the job twice.
This is possible if JobMonitor, which emits JobFinishedEvent runs (and emits) twice before getting cancelled.
> Fix threads race condition in handling of job completion

- genie-agent/src/main/java/com/netflix/genie/agent/execution/services/impl/JobSetupServiceImpl.java
- genie-agent/src/test/resources/JobSetupServiceImplSpec_run1.test.sh
- genie-agent/src/test/resources/JobSetupServiceImplSpec_run2.test.sh
- genie-web/src/integTest/resources/com/netflix/genie/web/apis/rest/v3/controllers/JobRestControllerIntegrationTests/runsh-agent.txt
Move cluster to setup before applications.
This matches V3 execution.
> Reorder resources setup in agent execution

- genie-docs/src/docs/asciidoc/_properties.adoc
- genie-web/src/integTest/java/com/netflix/genie/web/data/services/jpa/JpaApplicationPersistenceServiceImplIntegrationTest.java
- genie-web/src/integTest/java/com/netflix/genie/web/data/services/jpa/JpaClusterPersistenceServiceImplIntegrationTest.java
- genie-web/src/integTest/java/com/netflix/genie/web/data/services/jpa/JpaCommandPersistenceServiceImplIntegrationTest.java
- genie-web/src/integTest/java/com/netflix/genie/web/data/services/jpa/JpaJobPersistenceServiceImplIntegrationTest.java
- genie-web/src/integTest/resources/com/netflix/genie/web/data/services/jpa/JpaCommandPersistenceServiceImplIntegrationTest/deleteUnusedCommands/before.xml
- genie-web/src/integTest/resources/com/netflix/genie/web/data/services/jpa/cleanup.xml
- genie-web/src/main/java/com/netflix/genie/web/data/repositories/jpa/JpaApplicationRepository.java
- genie-web/src/main/java/com/netflix/genie/web/data/repositories/jpa/JpaBaseRepository.java
- genie-web/src/main/java/com/netflix/genie/web/data/repositories/jpa/JpaClusterRepository.java
- genie-web/src/main/java/com/netflix/genie/web/data/repositories/jpa/JpaCommandRepository.java
- genie-web/src/main/java/com/netflix/genie/web/data/repositories/jpa/JpaJobRepository.java
- genie-web/src/main/java/com/netflix/genie/web/data/services/ApplicationPersistenceService.java
- genie-web/src/main/java/com/netflix/genie/web/data/services/ClusterPersistenceService.java
- genie-web/src/main/java/com/netflix/genie/web/data/services/CommandPersistenceService.java
- genie-web/src/main/java/com/netflix/genie/web/data/services/JobPersistenceService.java
- genie-web/src/main/java/com/netflix/genie/web/data/services/jpa/JpaApplicationPersistenceServiceImpl.java
- genie-web/src/main/java/com/netflix/genie/web/data/services/jpa/JpaClusterPersistenceServiceImpl.java
- genie-web/src/main/java/com/netflix/genie/web/data/services/jpa/JpaCommandPersistenceServiceImpl.java
- genie-web/src/main/java/com/netflix/genie/web/data/services/jpa/JpaJobPersistenceServiceImpl.java
- genie-web/src/main/java/com/netflix/genie/web/tasks/leader/DatabaseCleanupTask.java
- genie-web/src/main/resources/db/migration/h2/V4_0_0_4__Add_Missing_Indicies.sql
- genie-web/src/main/resources/db/migration/mysql/V4_0_0_4__Add_Missing_Indicies.sql
- genie-web/src/main/resources/db/migration/postgresql/V4_0_0_4__Add_Missing_Indicies.sql
- genie-web/src/test/java/com/netflix/genie/web/tasks/leader/DatabaseCleanupTaskTest.java
- gradle.properties
- Upgrade dependencies to match internal versions
- Add missing indexes for frequently used health, metrics and cleanup queries
- Improve all database cleanup related task processes through transaction isolation, new arguments and overall consistency
> Database and other improvements

- build.gradle
- genie-agent/src/main/java/com/netflix/genie/agent/cli/CliAutoConfiguration.java
Match internal recommended version and attempt to avoid as many conflicts for consumers as possible
> Upgrade to OkHttp 4.3.1

- genie-agent/src/main/java/com/netflix/genie/agent/execution/services/impl/grpc/GRpcAgentFileStreamServiceImpl.java
- genie-agent/src/test/groovy/com/netflix/genie/agent/execution/services/impl/grpc/GRpcAgentFileStreamServiceImplSpec.groovy
Rather than an abrupt stop that cancels all ongoing transfers, implement a timed drain mechanism that allows transfers to complete.
> Implement soft shutdown of agent File Transfer service

- build.gradle
- genie-agent-app/build.gradle
- genie-agent/build.gradle
- genie-app/build.gradle
- genie-client/build.gradle
- genie-common-external/build.gradle
- genie-common-internal/build.gradle
- genie-common/build.gradle
- genie-proto/build.gradle
- genie-test-web/build.gradle
- genie-test/build.gradle
- genie-ui/build.gradle
- genie-web/build.gradle
- Remove PMD
- Address build file technical debt
> Build Improvements

- genie-client/src/integTest/java/com/netflix/genie/client/ClusterClientIntegrationTest.java
- genie-client/src/integTest/java/com/netflix/genie/client/CommandClientIntegrationTest.java
- genie-client/src/integTest/java/com/netflix/genie/client/JobClientIntegrationTest.java
This is a two stage change due to the docker image needing to be updated first for these tests to pass
> Modify client tests to support changes to the server

- genie-agent/src/main/java/com/netflix/genie/agent/execution/services/impl/grpc/GRpcAgentFileStreamServiceImpl.java
- genie-docs/src/docs/asciidoc/_metrics.adoc
- genie-docs/src/docs/asciidoc/_properties.adoc
- genie-web/src/main/java/com/netflix/genie/web/agent/apis/rpc/v4/endpoints/GRpcAgentFileStreamServiceImpl.java
- genie-web/src/main/java/com/netflix/genie/web/agent/services/impl/AgentRoutingServiceCuratorDiscoveryImpl.java
- genie-web/src/main/java/com/netflix/genie/web/properties/AgentFileStreamProperties.java
- genie-web/src/main/java/com/netflix/genie/web/spring/autoconfigure/agent/apis/rpc/v4/endpoints/AgentRpcEndpointsAutoConfiguration.java
- genie-web/src/main/java/com/netflix/genie/web/util/StreamBuffer.java
- genie-web/src/main/resources/genie-web-defaults.yml
- genie-web/src/test/groovy/com/netflix/genie/web/agent/apis/rpc/v4/endpoints/GRpcAgentFileStreamServiceImplSpec.groovy
- genie-web/src/test/groovy/com/netflix/genie/web/properties/AgentFileStreamPropertiesSpec.groovy
- genie-web/src/test/groovy/com/netflix/genie/web/util/StreamBufferSpec.groovy
- genie-web/src/test/java/com/netflix/genie/web/spring/autoconfigure/agent/apis/rpc/v4/endpoints/AgentRpcEndpointsAutoConfigurationTest.java
Refactoring of FileStream service that addresses concurrency issues and bugs surfaced during real-world testing.
> Improvements to agent file streaming

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Match internally supported version
Upgrade plugins to latest released versions as well
> Upgrade gradle

- genie-demo/src/docs/asciidoc/index.adoc
- genie-demo/src/main/docker/docker-compose.yml
- Fix missing dependency on presto container for Genie
- Improve demo instructions by providing more links, filling in Presto information, fixing the number of images/containers that come up, better highlight specific items, etc
> Improve Demo documentation and compose file

- genie-web/src/integTest/java/com/netflix/genie/web/data/services/impl/jpa/JpaPersistenceServiceImplApplicationsIntegrationTest.java
- genie-web/src/integTest/java/com/netflix/genie/web/data/services/impl/jpa/JpaPersistenceServiceImplClustersIntegrationTest.java
- genie-web/src/integTest/java/com/netflix/genie/web/data/services/impl/jpa/JpaPersistenceServiceImplCommandsIntegrationTest.java
- genie-web/src/integTest/java/com/netflix/genie/web/data/services/impl/jpa/JpaPersistenceServiceImplJobsIntegrationTest.java
- genie-web/src/integTest/java/com/netflix/genie/web/data/services/impl/jpa/JpaPersistenceServiceIntegrationTestBase.java
- genie-web/src/integTest/resources/com/netflix/genie/web/data/services/impl/jpa/persistence/jobs/search.xml
- genie-web/src/main/java/com/netflix/genie/web/data/services/impl/jpa/JpaPersistenceServiceImpl.java
Under the right circumstances, searching for Application/Cluster/Command can throw an error
> Fix entity search errors

- genie-agent/src/main/java/com/netflix/genie/agent/execution/services/impl/JobSetupServiceImpl.java
- genie-agent/src/main/java/com/netflix/genie/agent/execution/services/impl/ServicesAutoConfiguration.java
- genie-agent/src/main/java/com/netflix/genie/agent/execution/services/impl/grpc/GRpcAgentFileStreamServiceImpl.java
- genie-agent/src/main/java/com/netflix/genie/agent/properties/AgentProperties.java
- genie-agent/src/main/java/com/netflix/genie/agent/properties/JobSetupServiceProperties.java
- genie-agent/src/main/resources/genie-agent-defaults.yml
- genie-agent/src/test/groovy/com/netflix/genie/agent/execution/services/impl/JobSetupServiceImplSpec.groovy
- genie-agent/src/test/groovy/com/netflix/genie/agent/properties/AgentPropertiesSpec.groovy
- genie-agent/src/test/groovy/com/netflix/genie/agent/properties/JobSetupServicePropertiesSpec.groovy
- genie-agent/src/test/resources/JobSetupServiceImplSpec_run1.test.sh
- genie-agent/src/test/resources/JobSetupServiceImplSpec_run3.test.sh
- genie-docs/src/docs/asciidoc/_properties.adoc
- genie-web/src/integTest/resources/com/netflix/genie/web/apis/rest/v3/controllers/JobRestControllerIntegrationTests/runsh-agent.txt
- travis/buildViaTravis.sh
* Adjust verbosity of GRpcHeartBeatServiceImpl
* Configurable filtering of job environment debug dump
* Reorder properties
> Job environment debug dump filter (and more)

- genie-web/src/main/java/com/netflix/genie/web/agent/services/impl/AgentConnectionTrackingServiceImpl.java
- genie-web/src/test/groovy/com/netflix/genie/web/agent/services/impl/AgentConnectionTrackingServiceImplSpec.groovy
Locking of individual agent record could lead to thread interleaving that would notify routing service of events in the wrong order, resulting in an inconsistent state of the routing table. And jobs being killed by the leader due to being detected as AWOL.
> Fix concurrency bug in AgentConnectionTrackingService

- genie-common/src/main/java/com/netflix/genie/common/dto/JobExecution.java
- genie-common/src/test/java/com/netflix/genie/common/dto/JobExecutionTest.java
- genie-docs/src/docs/asciidoc/_metrics.adoc
- genie-docs/src/docs/asciidoc/_properties.adoc
- genie-docs/src/docs/asciidoc/concepts/_intro.adoc
- genie-docs/src/docs/asciidoc/concepts/_netflixDeployment.adoc
- genie-docs/src/docs/asciidoc/concepts/_netflixExample.adoc
- genie-docs/src/docs/asciidoc/index.adoc
- genie-web/src/integTest/java/com/netflix/genie/web/apis/rest/v3/controllers/Snippets.java
- genie-web/src/main/java/com/netflix/genie/web/agent/launchers/impl/LocalAgentLauncherImpl.java
- genie-web/src/main/java/com/netflix/genie/web/agent/launchers/impl/TitusAgentLauncherImpl.java
- genie-web/src/main/java/com/netflix/genie/web/data/services/impl/jpa/JpaPersistenceServiceImpl.java
- genie-web/src/main/java/com/netflix/genie/web/data/services/impl/jpa/converters/EntityV3DtoConverters.java
- genie-web/src/main/java/com/netflix/genie/web/data/services/impl/jpa/queries/projections/JobExecutionProjection.java
- genie-web/src/main/java/com/netflix/genie/web/dtos/TitusBatchJobRequest.java
- genie-web/src/main/java/com/netflix/genie/web/dtos/TitusBatchJobResponse.java
- genie-web/src/main/java/com/netflix/genie/web/properties/LocalAgentLauncherProperties.java
- genie-web/src/main/java/com/netflix/genie/web/properties/TitusAgentLauncherProperties.java
- genie-web/src/main/java/com/netflix/genie/web/services/impl/JobLaunchServiceImpl.java
- genie-web/src/main/java/com/netflix/genie/web/spring/autoconfigure/agent/launchers/AgentLaunchersAutoConfiguration.java
- genie-web/src/main/resources/genie-web-defaults.yml
- genie-web/src/test/groovy/com/netflix/genie/web/agent/launchers/impl/TitusAgentLauncherImplSpec.groovy
- genie-web/src/test/groovy/com/netflix/genie/web/properties/LocalAgentLauncherPropertiesSpec.groovy
- genie-web/src/test/groovy/com/netflix/genie/web/properties/TitusAgentLauncherPropertiesSpec.groovy
- genie-web/src/test/java/com/netflix/genie/web/spring/autoconfigure/agent/launchers/AgentLaunchersAutoConfigurationTest.java
Implement an AgentLauncher that leverages [Titus](https://netflix.github.io/titus/) to launch each job in a dedicated container, rather than launching on the same host.
> Implementation of Titus agent launcher

- build.gradle
- genie-ui/npm-shrinkwrap.json
- gradle/wrapper/gradle-wrapper.properties
Upgrade plugins to latest versions
NPM file got updated but seems to just be SHAs for integrity checks
> Upgrade Gradle to 6.7.1

- genie-docs/src/docs/asciidoc/_properties.adoc
- genie-web/src/main/java/com/netflix/genie/web/agent/launchers/impl/LocalAgentLauncherImpl.java
- genie-web/src/main/java/com/netflix/genie/web/properties/LocalAgentLauncherProperties.java
- genie-web/src/test/groovy/com/netflix/genie/web/agent/launchers/impl/LocalAgentLauncherImplSpec.groovy
- genie-web/src/test/groovy/com/netflix/genie/web/properties/LocalAgentLauncherPropertiesSpec.groovy
Allow setting a custom endpoint for agents to connect to via properties
> Templatize server hostname endpoint of local agent launcher

- genie-docs/src/docs/asciidoc/_properties.adoc
- genie-web/src/main/java/com/netflix/genie/web/agent/launchers/impl/TitusAgentLauncherImpl.java
- genie-web/src/main/java/com/netflix/genie/web/dtos/TitusBatchJobRequest.java
- genie-web/src/main/java/com/netflix/genie/web/properties/TitusAgentLauncherProperties.java
- genie-web/src/test/groovy/com/netflix/genie/web/agent/launchers/impl/TitusAgentLauncherImplSpec.groovy
- genie-web/src/test/groovy/com/netflix/genie/web/properties/TitusAgentLauncherPropertiesSpec.groovy
Also make additional properties dynamic to improve rollout flexibility
> Add missing fields to Titus launcher

- genie-docs/src/docs/asciidoc/_properties.adoc
- genie-web/src/main/java/com/netflix/genie/web/agent/launchers/dtos/TitusBatchJobRequest.java
- genie-web/src/main/java/com/netflix/genie/web/agent/launchers/impl/TitusAgentLauncherImpl.java
- genie-web/src/main/java/com/netflix/genie/web/properties/TitusAgentLauncherProperties.java
- genie-web/src/test/groovy/com/netflix/genie/web/properties/TitusAgentLauncherPropertiesSpec.groovy
stack, detail, sequence
Also add exception to adapter API
> Add missing fields to Titus request for job grouping

- genie-web/src/main/java/com/netflix/genie/web/agent/launchers/impl/TitusAgentLauncherImpl.java
…ial race condition downstream
> Create new instance for attributes and security group to avoid potential race condition in downstream

- travis/buildViaTravis.sh
```
The job exceeded the maximum log length, and has been terminated.
```
👎
> buildViaTravis.sh: run with --stacktrace flag

- build.gradle
- genie-web/src/integTest/java/com/netflix/genie/web/data/services/impl/jpa/JpaPersistenceServiceImplCommandsIntegrationTest.java
- genie-web/src/main/java/com/netflix/genie/web/data/services/PersistenceService.java
- genie-web/src/main/java/com/netflix/genie/web/data/services/impl/jpa/JpaPersistenceServiceImpl.java
- genie-web/src/main/java/com/netflix/genie/web/data/services/impl/jpa/entities/CommandEntity.java
- genie-web/src/main/java/com/netflix/genie/web/data/services/impl/jpa/repositories/JpaCommandRepository.java
- genie-web/src/main/java/com/netflix/genie/web/tasks/leader/DatabaseCleanupTask.java
- genie-web/src/test/java/com/netflix/genie/web/tasks/leader/DatabaseCleanupTaskTest.java
- gradle/wrapper/gradle-wrapper.properties
> Split command deactivation into two batched queries

- genie-docs/src/docs/asciidoc/concepts/_dataModel.adoc
> Fix broken references in data model documentation

- build.gradle
- genie-proto/build.gradle
- gradle.properties
Also put in patch fix to support M1 Macs
> Align grpc and protobuf dependencies with internal versions

- build.gradle
- genie-proto/build.gradle
Better support for Mac M1 machines
> Upgrade testcontainers

- build.gradle
- gradle.properties
> Align dependencies

- build.gradle
- gradle.properties
- Spring boot -> 2.6.4
- Spring Cloud AWS -> 2.4.0
- Spring Cloud -> 2021.0.1
> Dependency version alignment

- genie-web/src/integTest/java/com/netflix/genie/web/data/services/impl/jpa/JpaPersistenceServiceImplJobsIntegrationTest.java
- genie-web/src/integTest/resources/com/netflix/genie/web/data/services/impl/jpa/persistence/jobs/jobSpecification.xml
- genie-web/src/main/java/com/netflix/genie/web/data/services/impl/jpa/entities/JobEntity.java
Same commits applies to the 4.2.x branch.
> Make the eagerly loaded job dependencies and env variables to use the default fetch types on 4.2.x

- genie-web/src/main/java/com/netflix/genie/web/data/services/impl/jpa/converters/IntegerToLongConverter.java
- genie-web/src/main/java/com/netflix/genie/web/data/services/impl/jpa/entities/CommandEntity.java
- genie-web/src/main/java/com/netflix/genie/web/data/services/impl/jpa/entities/JobEntity.java
- genie-web/src/main/resources/db/migration/h2/V4_3_0_0__Containers.sql
- genie-web/src/main/resources/db/migration/mysql/V4_3_0_0__Containers.sql
- genie-web/src/main/resources/db/migration/postgresql/V4_3_0_0__Containers.sql
Instead of changing the memory from long to int in application, we can use a customized converter to achieve the same thing without creating a mess. related to https://github.com/Netflix/genie/pull/1177
> use converter to switch value between int and long

- genie-web/src/integTest/java/com/netflix/genie/web/data/services/impl/jpa/JpaPersistenceServiceImplFilesIntegrationTest.java
- genie-web/src/main/java/com/netflix/genie/web/data/services/PersistenceService.java
- genie-web/src/main/java/com/netflix/genie/web/data/services/impl/jpa/JpaPersistenceServiceImpl.java
- genie-web/src/main/java/com/netflix/genie/web/data/services/impl/jpa/repositories/JpaFileRepository.java
- genie-web/src/main/java/com/netflix/genie/web/properties/DatabaseCleanupProperties.java
- genie-web/src/main/java/com/netflix/genie/web/tasks/leader/DatabaseCleanupTask.java
- genie-web/src/test/java/com/netflix/genie/web/properties/DatabaseCleanupPropertiesTest.java
- genie-web/src/test/java/com/netflix/genie/web/tasks/leader/DatabaseCleanupTaskTest.java
Break down the file deletion clean up task to perform clean up and look up in smaller trunks.
> Files deletion cleanup improvements

- genie-web/src/main/java/com/netflix/genie/web/agent/launchers/dtos/TitusBatchJobRequest.java
- genie-web/src/main/java/com/netflix/genie/web/agent/launchers/impl/TitusAgentLauncherImpl.java
- genie-web/src/main/java/com/netflix/genie/web/agent/launchers/impl/TitusNetoworkMode.java
- genie-web/src/main/java/com/netflix/genie/web/properties/TitusAgentLauncherProperties.java
- genie-web/src/test/groovy/com/netflix/genie/web/agent/launchers/impl/TitusAgentLauncherImplSpec.groovy
Add a network configuration section to titus batch request class so that different network mode can be used.
> add network config to titus request

- .github/workflows/genie-build.yml
- build.gradle
- genie-app/src/main/docker/Dockerfile
JDK 17 upgrade for only genie servers
> JDK 17 upgrade for only genie servers

- .github/workflows/genie-build.yml
- build.gradle
- genie-app/src/main/docker/Dockerfile
Revert "Temporarily remove the integration test for unblocking:https://github.com/Netflix/genie/commit/12a6641bdaca283ffb4828aee6bb6f122e0e2bc8
> Revert "Temporarily remove the integration test for unblocking" 

- .github/workflows/genie-build.yml
Comment out Codecov for unblocking
> Comment out Codecov for unblocking

- genie-client/src/integTest/java/com/netflix/genie/client/GenieClientIntegrationTestBase.java
- genie-web/src/integTest/java/com/netflix/genie/web/data/services/impl/jpa/JpaPersistenceServiceImplTagsIntegrationTest.java
- genie-web/src/main/java/com/netflix/genie/web/data/services/PersistenceService.java
- genie-web/src/main/java/com/netflix/genie/web/data/services/impl/jpa/JpaPersistenceServiceImpl.java
- genie-web/src/main/java/com/netflix/genie/web/data/services/impl/jpa/repositories/JpaFileRepository.java
- genie-web/src/main/java/com/netflix/genie/web/data/services/impl/jpa/repositories/JpaTagRepository.java
- genie-web/src/main/java/com/netflix/genie/web/properties/DatabaseCleanupProperties.java
- genie-web/src/main/java/com/netflix/genie/web/tasks/leader/DatabaseCleanupTask.java
- genie-web/src/test/java/com/netflix/genie/web/properties/DatabaseCleanupPropertiesTest.java
- genie-web/src/test/java/com/netflix/genie/web/tasks/leader/DatabaseCleanupTaskTest.java
Similar to PR #1184, break down the tag deletion cleanup task to perform lookup and cleanup in smaller chunks.
> Improve delete unused tags to be able to process in chunks

- genie-agent-app/build.gradle
- genie-agent/build.gradle
> Genie agent JDK17 upgrade

- build.gradle
Minor Fix for Genie OSS Upgrade: Update codeCoverageReport dependsOn
> Minor Fix for Genie OSS Upgrade: Update codeCoverageReport dependsOn

- build.gradle
Genie OSS SBN 3 Upgrade Minor Fix: Update codeCoverageReport dependsOn
> Genie OSS SBN 3 Upgrade Minor Fix: Update codeCoverageReport dependsOn

- genie-agent/src/main/java/com/netflix/genie/agent/execution/services/impl/grpc/GRpcAgentFileStreamServiceImpl.java
Add NPE check before cancelling agent scheduled task
> Add NPE check before cancelling agent scheduled task

- .github/workflows/genie-build.yml
Fix the issue of concurrent pushes to the gh-pages branch
> Fix the issue of concurrent pushes to the gh-pages branch
